### ISSUE TITLE
DirectoryWebhookControllerTest fails on vanilla install

### ISSUE THREAD

**Issue by james-s-turner** [SymphonyOSF/app-auth-example#4]
I have just cloned repo and run 
```mvn clean install```
I see the following build errors
```
Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.072 sec <<< FAILURE! - in com.symphony.example.pods.DirectoryWebhookControllerTest
updatePodInfo(com.symphony.example.pods.DirectoryWebhookControllerTest)  Time elapsed: 0.027 sec  <<< FAILURE!
java.lang.AssertionError: Status expected:<200> but was:<400>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:54)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:81)
	at org.springframework.test.web.servlet.result.StatusResultMatchers$10.match(StatusResultMatchers.java:664)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:171)
	at io.restassured.module.mockmvc.internal.ValidatableMockMvcResponseImpl.expect(ValidatableMockMvcResponseImpl.java:48)
	at io.restassured.module.mockmvc.internal.ValidatableMockMvcResponseImpl.assertThat(ValidatableMockMvcResponseImpl.java:56)
	at com.symphony.example.pods.DirectoryWebhookControllerTest.updatePodInfo(DirectoryWebhookControllerTest.java:87)

updatePodInfoBadKey(com.symphony.example.pods.DirectoryWebhookControllerTest)  Time elapsed: 0.017 sec  <<< FAILURE!
java.lang.AssertionError: Status expected:<401> but was:<400>
	at org.springframework.test.util.AssertionErrors.fail(AssertionErrors.java:54)
	at org.springframework.test.util.AssertionErrors.assertEquals(AssertionErrors.java:81)
	at org.springframework.test.web.servlet.result.StatusResultMatchers$10.match(StatusResultMatchers.java:664)
	at org.springframework.test.web.servlet.MockMvc$1.andExpect(MockMvc.java:171)
	at io.restassured.module.mockmvc.internal.ValidatableMockMvcResponseImpl.expect(ValidatableMockMvcResponseImpl.java:48)
	at io.restassured.module.mockmvc.internal.ValidatableMockMvcResponseImpl.assertThat(ValidatableMockMvcResponseImpl.java:56)
	at com.symphony.example.pods.DirectoryWebhookControllerTest.updatePodInfoBadKey(DirectoryWebhookControllerTest.java:117)

Running com.symphony.example.pods.PodDirectoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.symphony.example.pods.PodDirectoryTest
Running com.symphony.example.users.UserServiceTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in com.symphony.example.users.UserServiceTest
Running com.symphony.example.utils.SecurityKeyUtilsTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.03 sec - in com.symphony.example.utils.SecurityKeyUtilsTest
Running com.symphony.example.web.AppConfigControllerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 sec - in com.symphony.example.web.AppConfigControllerTest
Running com.symphony.symphony.client.HttpClientBuilderTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 sec - in com.symphony.symphony.client.HttpClientBuilderTest
Running com.symphony.symphony.client.SymphonyClientFactoryTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec - in com.symphony.symphony.client.SymphonyClientFactoryTest
2018-02-06 10:29:07.075  INFO 40583 --- [       Thread-3] o.s.c.support.GenericApplicationContext  : Closing org.springframework.context.support.GenericApplicationContext@5e922647: startup date [Tue Feb 06 10:29:05 GMT 2018]; root of context hierarchy
2018-02-06 10:29:07.076  INFO 40583 --- [       Thread-2] o.s.w.c.s.GenericWebApplicationContext   : Closing org.springframework.web.context.support.GenericWebApplicationContext@1500b2f3: startup date [Tue Feb 06 10:29:03 GMT 2018]; root of context hierarchy

Results :

Failed tests: 
  DirectoryWebhookControllerTest.updatePodInfo:87 Status expected:<200> but was:<400>
  DirectoryWebhookControllerTest.updatePodInfoBadKey:117 Status expected:<401> but was:<400>
```

Running OSx 10.10.5, Java 1.8.0_131, Maven 3.5.2

**Comment by dnsymphony** [comment]
Cannot reproduce. I think I noticed and fixed this already.
